// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hthfpfrsmzbxvdjgxdpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aGZwZnJzbXpieHZkamd4ZHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NzE3NTMsImV4cCI6MjA1NDE0Nzc1M30.90P-xXnY5GN3OoFTsTUlFlxjdnRfwRTPmEmUfDrhYts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);